\context ChordNames
	\chords {
	% intro
	a1 g1 a1 g1

	% glooooria a dios en el cieeelo...
	a1 g1 a1 g1
	a1 g1 a1 g1

	% glooooria a dios en el cieeelo...
	a1 g1 a1 g1
	a1 g1 a1 g1

	% te alabamos...
	c1 a1 c1 a1

	% te damos gracias por...
	a1 g1 a1 g1
	a1 g1 a1 g1

	% dios padre todopoderoso
	fis1:m g1
	a1 g1
	d1 g1
	a1 a1

	% tu que quitas...
	a1:m g1 d1 a1:m
	a1:m g1 d1 c1
	c1 g1 d1 a1 a1

	% porque solamente tu eres santo...
	fis1:m g1
	a1 g1
	d1 g1
	a1 g1

	% glooooria a dios en el cieeelo...
	a1 g1 a1 g1
	a1 g1 a1 g1

	% glooooria a dios en el cieeelo...
	a1 g1 a1 g1
	a1 g1 a1 g1

	% amen
	d1 g1 a1 a1
	}
